/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    DemandModal: typeof import('./src/components/DemandModal.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    InfoDemand: typeof import('./src/components/InfoDemand.vue')['default']
    InfoModal: typeof import('./src/components/InfoModal.vue')['default']
    MapLocation: typeof import('./src/components/MapLocation.vue')['default']
  }
}
